server:
  port: 9000

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**

            - id: enrollments
              uri: lb://enrollments
              predicates:
                - Path=/enrollments/**

            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/courses/**

            - id: certificateService
              uri: lb://certificateService
              predicates:
                - Path=/certificates/**

            - id: assessment-service
              uri: lb://assessment-service
              predicates:
                - Path=/quizzes/**

            - id: Payment-Service
              uri: lb://Payment-Service
              predicates:
                - Path=/payments/**
  main:
    web-application-type: reactive

app:
  jwt:
    secret: mysecretkey-online-learning-platform-system8182056

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0   # trace all requests
    propagation:
      type: B3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true