jwt:
  expiration: 360000
  secret: mysecretkey-online-learning-platform-system8182056

server:
  port: 9009

spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/edutrackauthservice?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0   # trace all requests
    propagation:
      type: B3